name: homeservices_marketplace

description: A new Flutter project to manage home services.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.12.0
  firebase_auth: ^4.12.0
  cloud_firestore: ^4.12.0
  google_maps_flutter: ^2.3.0
  flutter_riverpod: ^2.0.0
  stripe_flutter: ^6.0.0
  socket_io_client: ^2.0.0
  cupertino_icons: ^1.0.3
  http: ^0.14.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true